name: Generate Snake

on:
  schedule:
    # Runs at 12:00 AM UTC every day
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        with:
          github_user_name: vasundharasaxena
          outputs: dist/snake.svg

      - name: Upload Snake
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg
